### ISSUE TITLE
The highlighting of the code breaks at the symbol ";" in line

### ISSUE THREAD

**Issue by CzarOfScripts** [helsmy/vscode-autohotkey#9]
![image](https://user-images.githubusercontent.com/78804737/162587263-e454467a-6a84-4597-a26f-b6d9d2f4ab62.png)

**Comment by CzarOfScripts** [comment]
An error, it's not because of the ";" character, if you add one more quote - everything is fine.

**Comment by helsmy** [comment]
Tmlanguage vscode used for highlighting is based on line text. In other word, each token for highlighting must be placed in one line. But, multiline string, namely continuation section , in ahk is started with `"\n[\s\t]*(`, which is impossible to be matched 100% accuratly. I use pattern: starting with `"`, ending with `\)\s*"` now. If you have any better sollution you can commnet here or pull requset it, thanks. 😄

**Comment by helsmy** [comment]
I pushed a commit that eliminated difference between two types of strings. All strings will match two `"` regardless if there is `\n` or not. I thought it should be accurate enough for most cases.

**Comment by CzarOfScripts** [comment]
Still an error. I will attach the code.
```AutoHotKey
addRow(index, name, artic, link, title, manufacturer, crossArtic, price, stored)
{
	stored := RegExReplace(stored, "&gt;", ">")

	Cell := Application.Cells(Application.Rows.Count, 1).End(-4162)

	Cell.offset(1, 0).value := index
	Cell.offset(1, 1).value := name
	Cell.offset(1, 2).value := artic
	; Cell.offset(1, 3).Formula := "=HYPERLINK(""" link """, """ link """)"
	Application.ActiveSheet.Hyperlinks.Add(Cell.offset(1, 3), link)
	Cell.offset(1, 4).value := title
	; Cell.offset(1, 4).WrapText := true
	Cell.offset(1, 5).value := manufacturer
	Cell.offset(1, 6).value := crossArtic
	Cell.offset(1, 7).value := price
	Cell.offset(1, 8).value := (stored ? "Так" : "Ні") " (" (stored == "" ? "no info" : stored) ")"

	Cell.offset(1, 2).NumberFormat := "@"
}
```

![image](https://user-images.githubusercontent.com/78804737/164956868-1f37494d-c76a-4eb4-b18c-7b916f63bf1e.png)
